const DEFAULTS={enabled:false,intervalMinutes:5,keywords:'rolex,omega,tudor,breitling,cartier,iwc,grand seiko,longines',excludedKeywords:'replica,homage,inspired style,parts only,wanted',maximumAsk:10000,minimumScore:55,autoScroll:true,listings:{}};
const ids=['keywords','excludedKeywords','maximumAsk','minimumScore','intervalMinutes','autoScroll'];
document.addEventListener('DOMContentLoaded',render);
document.querySelector('#toggle').addEventListener('click',toggle);
document.querySelector('#scanNow').addEventListener('click',scanNow);

async function render(){const state=await chrome.storage.local.get(DEFAULTS);for(const id of ids){const el=document.querySelector(`#${id}`);if(el.type==='checkbox')el.checked=Boolean(state[id]);else el.value=state[id];}document.querySelector('#statusDot').classList.toggle('on',state.enabled);const toggle=document.querySelector('#toggle');toggle.textContent=state.enabled?'Stop scanner':'Start on this search';toggle.classList.toggle('danger',state.enabled);document.querySelector('#scanNow').disabled=!state.enabled;if(state.pausedReason)show(state.pausedReason);const flagged=Object.values(state.listings||{}).filter(x=>x.score>=Number(state.minimumScore)).sort((a,b)=>b.score-a.score||String(b.lastSeenAt).localeCompare(String(a.lastSeenAt))).slice(0,12);document.querySelector('#count').textContent=`${flagged.length} shown`;document.querySelector('#listings').innerHTML=flagged.length?flagged.map(card).join(''):'<div class="empty">No opportunities flagged yet.</div>';}
async function toggle(){const state=await chrome.storage.local.get(DEFAULTS);if(state.enabled){await chrome.runtime.sendMessage({type:'STOP_SCANNER'});show('Scanner stopped.');}else{const settings=values();const result=await chrome.runtime.sendMessage({type:'START_SCANNER',settings});show(result.ok?'Scanner started on this Marketplace search.':result.error);}await render();}
async function scanNow(){const result=await chrome.runtime.sendMessage({type:'SCAN_NOW'});show(result.ok?`Scanned ${result.count} visible listings.`:result.error);await render();}
function values(){return Object.fromEntries(ids.map(id=>{const el=document.querySelector(`#${id}`);return[id,el.type==='checkbox'?el.checked:el.type==='number'?Number(el.value):el.value]}));}
function show(text){const el=document.querySelector('#message');el.textContent=text;el.classList.toggle('show',Boolean(text));}
function card(item){const price=item.price?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(item.price):'Price unknown';return `<a class="listing" href="${escapeHtml(item.url)}" target="_blank"><div class="listingTop"><span>${escapeHtml(item.title)}</span><span class="score">${item.score}/100</span></div><div class="meta">${price} · ${escapeHtml((item.reasons||[]).join(' · '))}</div></a>`;}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));}
